# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build ./CarAuctionManagementSystem.Application/CarAuctionManagementSystem.Application.csproj --configuration Release --no-restore
      
    - name: Publish
      run: dotnet publish ./CarAuctionManagementSystem.Application/CarAuctionManagementSystem.Application.csproj --configuration Release --no-build --output ./publish

    - name: run-tests
      uses: alsi-lawr/dotnet-test-coverlet@v1
      with:
        project: ./CarAuctionManagementSystem.Tests/CarAuctionManagementSystem.Tests.csproj
        collect: XPlat Code Coverage
        coverlet_args: '--format cobertura --format html'
        dotnet-version: 9.0.x
        
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage.cobertura.xml

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: car-auction-management-system
        path: ./publish
